name: moundenv

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

# Core dependencies required for the environment
dependencies:
  - python=3.10.19
  - pytorch=2.7.1
  - torchvision=0.22.1
  - pytorch-cuda=11.8
  - numpy=2.2.6
  - pandas=2.3.3
  - pillow=11.3.0
  - scipy=1.15.2
  - scikit-learn=1.7.2
  - pip

# Additional packages installed via pip
  - pip:
      - torchaudio==2.7.1+cu118
      - detectron2==0.6
      - opencv-python==4.13.0
      - matplotlib==3.10.7
      - pycocotools==2.0.10
      - openpyxl==3.1.5
      - fvcore==0.1.5.post20221221
      - iopath==0.1.9
